// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class Image
{
    public Guid ImageId { get; set; }

    public int UserId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public DateTime? UploadedAt { get; set; }

    public virtual ICollection<SkinAnalysisResult> SkinAnalysisResults { get; set; } = new List<SkinAnalysisResult>();

    public virtual User User { get; set; }
}