// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class Kolvideo
{
    public Guid VideoId { get; set; }

    public Guid AffiliateProfileId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string VideoUrl { get; set; }

    public Guid ProductId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActive { get; set; }

    public virtual AffiliateProfile AffiliateProfile { get; set; }

    public virtual Product Product { get; set; }
}