// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics.Models;

public partial class SkinAnalysisResult
{
    public Guid ResultId { get; set; }

    public Guid ImageId { get; set; }

    public string AnalysisData { get; set; }

    public DateTime? AnalyzedAt { get; set; }

    public virtual Image Image { get; set; }
}